### ISSUE TITLE
ActionDispatch::Cookies::CookieOverflow

### ISSUE THREAD

**Issue by rcaught** [ausaccessfed/validator-service#139]
When no `mail, common name, display name, targetedID` present.

```
I, [2017-07-11T01:52:19.798087 #4877]  INFO -- : [fa23a62e-5ddb-402c-a8a8-f8f66073962a] Started GET "/auth/login" for 210.11.182.2 at 2017-07-11 01:52:19 +0000
D, [2017-07-11T01:52:19.800885 #4877] DEBUG -- : [fa23a62e-5ddb-402c-a8a8-f8f66073962a]   FederationAttribute Load (0.9ms)  SELECT  `federation_attributes`.* FROM `federation_attributes` WHERE `federation_attributes`.`internal_alias` = 'persistent_id' LIMIT 1
D, [2017-07-11T01:52:19.802179 #4877] DEBUG -- : [fa23a62e-5ddb-402c-a8a8-f8f66073962a]   FederationAttribute Load (0.8ms)  SELECT  `federation_attributes`.* FROM `federation_attributes` WHERE `federation_attributes`.`internal_alias` = 'mail' LIMIT 1
F, [2017-07-11T01:52:19.804007 #4877] FATAL -- : [fa23a62e-5ddb-402c-a8a8-f8f66073962a]
F, [2017-07-11T01:52:19.804064 #4877] FATAL -- : [fa23a62e-5ddb-402c-a8a8-f8f66073962a] ActionDispatch::Cookies::CookieOverflow (ActionDispatch::Cookies::CookieOverflow):
F, [2017-07-11T01:52:19.804121 #4877] FATAL -- : [fa23a62e-5ddb-402c-a8a8-f8f66073962a]
F, [2017-07-11T01:52:19.804201 #4877] FATAL -- : [fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:594:in `commit'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:465:in `[]='
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/session/cookie_store.rb:117:in `set_cookie'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:363:in `commit_session'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:234:in `context'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/callbacks.rb:90:in `run_callbacks'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:36:in `call_app'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:24:in `block in call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:69:in `block in tagged'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:26:in `tagged'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/tagged_logging.rb:69:in `tagged'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/rack/logger.rb:24:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/request_id.rb:24:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/actionpack-5.0.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/secure_headers-3.5.1/lib/secure_headers/middleware.rb:12:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/railties-5.0.4/lib/rails/engine.rb:522:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
[fa23a62e-5ddb-402c-a8a8-f8f66073962a] vendor/bundle/ruby/2.3.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by smangelsdorf** [comment]
The real bug here is that we're using cookie-based session storage, yeah?
